version: '3'

services:
#  nightingale-mongodb:
#    image: mongodb/mongodb-community-server:latest
#    ports:
#      - "27017:27017"
#    volumes:
#      - mongodb_data:/data/db

  nightingale-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6400:6400"
    volumes:
      - ./DataMaintenance/cert_file:/app/DataMaintenance/cert_file
#    depends_on:
#      - nightingale-mongodb

#  nightingale-grafana:
#    image: grafana/grafana-enterprise
#    ports:
#      - "3000:3000"
#    volumes:
#      - grafana-storage:/var/lib/grafana

  nightingale-nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nightingale-api

volumes:
  # mongodb_data: {}
  grafana-storage: {}

